"""
#TODO: docs
"""

#########################   These values should not need to be changed between runs, but may change depending on your
#         CONFIG        #   operating system, filepaths, and preferred output location.
#########################

ww_source_dir = r"W:\documents\2026_RT_Reports"         # Parent directory of the YYYYMMDD_RT_Report folders
snm_source_dir = r"J:\paperwork\0_UCSB_DWR_Project\2026_RT_Reports"
rt_report_pattern = "_RT_report"

ww_table_data = {
    "01" : "Pacific Northwest",
    "02" : "North Continental",
    "03" : "South Continental",
    "04" : "Intermountain",
}

snm_table_data = {
    "05" : {"title": "Sierra Nevada",    "jpg_id": "1"},
    "10" : {"title": "Elevation Banded", "jpg_id": "2"},
}
#########################
#       END CONFIG      #
#########################

import re
import glob
import os
import shutil
import subprocess
from pathlib import Path
import pandas as pd
from jinja2 import Template, Environment, FileSystemLoader
import argparse

def get_output_dir(date:int, report_type:str) -> str:
    # TODO: docs
    source_dir = None
    match report_type:
        case 'WW':
            source_dir = ww_source_dir
        case 'SNM':
            source_dir = snm_source_dir
        case _:
            raise Exception(f"Unrecognized report type: {report_type}")
    output_dir=os.path.join(source_dir, str(date) + rt_report_pattern, "Report", f"{date}_{report_type}_TEXtables")
    return output_dir


def escape_latex(text):
    """
    Escape special LaTeX characters in text.
    """
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        # '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\^{}',
        '\\': r'\textbackslash{}',
        # '§': r'\S{}',
        '†': r'$\dagger$'
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def interpret_ids(ids: str, report_type: str) -> list[str]:
    """
    Interprets the --tables regex flag

    :param ids: String value of the --tables flag as generated by parser.parse_args()
    :param report_type: Type of report to interpret figures for. Acceptable values: "WW", "SNM"
    :return: List of interpreted table IDs to generate tables for
    :rtype: list[str]
    """

    # Determine list of table ids based on report type
    all_ids = set()
    match report_type:
        case 'WW':
            all_ids = set(ww_table_data.keys())
        case 'SNM':
            all_ids = set(snm_table_data.keys())
        case _:
            raise Exception(f"Unrecognized report type: {report_type}")

    # Parse the argument passed into --tables
    patterns = ids.split(",")
    id_list = set()

    for pattern in patterns:
        pattern = pattern.lower()
        # Shortcut search when all or no IDs are specified
        if pattern in ["all","."]:
            return sorted(all_ids)
        elif pattern in ["none",""]:
            return []

        # Modify regular expression syntax to better support * wildcard
        regex_pattern = "^" + re.escape(pattern).replace("\\*", ".*") + "$"
        regex = re.compile(regex_pattern)

        # Match the pattern against all possible IDs
        pattern_found = False
        for id in all_ids-id_list:
            if regex.match(id):
                id_list.add(id)
                pattern_found = True
        if not pattern_found:
            # Pattern does not match any name in all_ids
            if pattern == "0":
                raise Exception(f"--tables pattern '0' not recognized! Did you mean 'none'?")
            else:
                raise Exception(f"--tables pattern '{pattern}' not recognized!")

    return sorted(id_list)


def compile_standalone_table(tex_path: Path, verbose=False) -> Path | None:
    """
    Compiles a standalone .tex file to PDF using pdflatex.

    Runs pdflatex with the output directory set to a temporary LaTeX/ folder
    beside the TEXtables/ directory, then moves only the .pdf back into
    TEXtables/ alongside the .tex source. All auxiliary files (.aux, .log,
    .synctex.gz, etc.) remain in LaTeX/.

    :param tex_path: Path to the standalone .tex file in TEXtables/
    :param verbose: Enable verbose output messages. Default: False
    :return: Path to the compiled .pdf in TEXtables/, or None on failure
    :rtype: Path | None
    """
    latex_dir = tex_path.parent.parent / "LaTeX"
    latex_dir.mkdir(parents=True, exist_ok=True)

    try:
        subprocess.run(
            [
                "pdflatex",
                "-interaction=nonstopmode",
                f"-output-directory={latex_dir}",
                str(tex_path),
            ],
            cwd=tex_path.parent,
            check=True,
            capture_output=not verbose,
        )
    except subprocess.CalledProcessError as e:
        print(f"Error: pdflatex failed for {tex_path.name}. Check {latex_dir / tex_path.with_suffix('.log').name} for details.")
        if verbose: print(e)
        return None

    # Move only the PDF back to TEXtables/ — leave all other aux files in LaTeX/
    pdf_in_latex = latex_dir / tex_path.with_suffix(".pdf").name
    pdf_in_textables = tex_path.with_suffix(".pdf")
    shutil.move(str(pdf_in_latex), str(pdf_in_textables))

    if verbose: print(f"Compiled PDF saved to {pdf_in_textables}")
    return pdf_in_textables


def convert_pdf_to_jpg(pdf_path: Path, output_dir: Path, verbose=False, jpg_stem: str = None, prompt_user=False) -> Path | None:
    """
    Converts the first page of a PDF to a JPG using PyMuPDF (fitz).

    The JPG is saved directly to output_dir. If jpg_stem is provided it is used
    as the output filename stem; otherwise the PDF's own stem is used.

    :param pdf_path: Path to the PDF file to convert
    :param output_dir: Directory to save the output .jpg (Report/)
    :param verbose: Enable verbose output messages. Default: False
    :param jpg_stem: Output filename stem (without extension). Default: pdf_path.stem
    :param prompt_user: Prompt before overwriting an existing .jpg. Default: False
    :return: Path to the saved .jpg, or None on failure
    :rtype: Path | None
    """
    import fitz  # PyMuPDF

    stem = jpg_stem if jpg_stem else pdf_path.stem
    jpg_path = output_dir / f"{stem}.jpg"
    if prompt_user and jpg_path.exists():
        print(f"{jpg_path.name} already exists and will be overwritten! Continue? (y/N)")
        while True:
            user_answer = input("> ").strip().lower()
            if user_answer in ["y", "yes"]:
                break
            elif user_answer in ["", "n", "no"]:
                print(f"Skipping JPG conversion for {jpg_path.name}")
                return None
            else:
                print("Invalid input. Please enter y or n.")
    while True:
        try:
            doc = fitz.open(str(pdf_path))
            page = doc[0]
            # 300 DPI: default PDF unit is 72 DPI, so matrix scale = 300/72
            mat = fitz.Matrix(300 / 72, 300 / 72)
            pix = page.get_pixmap(matrix=mat, colorspace=fitz.csRGB)
            pix.save(str(jpg_path))
            doc.close()
            break
        except Exception as e:
            if "Permission denied" in str(e) or isinstance(e, PermissionError):
                print(f"Error: {jpg_path.name} is open in another program. Close it and press Enter to retry, or type 's' to skip.")
                if input("> ").strip().lower() == "s":
                    print(f"Skipping JPG conversion for {jpg_path.name}.")
                    return None
            else:
                print(f"Error: failed to convert {pdf_path.name} to JPG: {e}")
                return None

    if verbose: print(f"JPG saved to {jpg_path}")
    return jpg_path


def generate_tables(report_type: str, date: int, ids: str, verbose=False, prompt_user=False, standalone=False) -> None:
    # TODO: verbose
    """
    # TODO: docs
    """
    # Define output directory
    date_str = str(date)
    report_dir = None
    table_data = None
    match report_type:
        case "WW":
            report_dir = os.path.join(ww_source_dir, str(date) + rt_report_pattern)
            table_data = ww_table_data
            if standalone:
                standalone = False # No standalone table support for WW
                if verbose: print(f"Standalone tables are not supported for WW. Ignoring --standalone flag.")
        case "SNM":
            report_dir = os.path.join(snm_source_dir, str(date) + rt_report_pattern)
            table_data = snm_table_data
        case _:
            raise Exception(f"Unrecognized report type: {report_type}")

    use_this_dir = glob.glob(os.path.join(report_dir, "*UseThis*"))[0]
    table_dir = os.path.join(use_this_dir, "Tables")

    # Determine which tables to generate
    id_list = interpret_ids(ids, report_type)

    # Merge WW tables 04a and 04b into a single table
    # if report_type == "WW" and "04" in id_list:
    #     table04a = os.path.join(table_dir, f"INMT1_{date}_Table04a_final.csv")
    #     table04b = os.path.join(table_dir, f"INMT2_{date}_Table04b_final.csv")
    #     table04_output = os.path.join(table_dir, f"INMT0_{date}_Table04_final.csv")
    #     if not os.path.exists(table04_output):
    #         merge_swe_csv(table04a, table04b, table04_output)

    # File overwrite choices
    yes_to_all = False
    no_to_all = False

    # Generate tables
    for table_id in id_list:
        # Handle overwriting file
        if no_to_all:
            break
        if standalone:
            output_filename = f"{date}_{report_type}_Table{table_id}_standalone.tex"
        else:
            output_filename = f"{date}_{report_type}_Table{table_id}.tex"
        output_filepath = Path(get_output_dir(date, report_type)) / output_filename
        if prompt_user and os.path.exists(output_filepath) and not yes_to_all:
            print(f"{output_filename} already exists and will be overwritten! Continue?")
            print("Options: [y]es, [n]o, [ya] yes to all, [na] no to all (default: no)")
            while True:
                user_answer = input("> ").strip().lower()
                if user_answer in ["y", "yes"]:
                    break  # Generate table_id
                elif user_answer in ["ya"]:
                    yes_to_all = True
                    break  # Generate all table_ids in id_list
                elif user_answer in ["", "n", "no"]:
                    print(f"Skipping table generation for Table{table_id}")
                    table_id = None
                    break  # Skip this table only
                elif user_answer in ["na"]:
                    print("Safely aborting table generation...")
                    no_to_all = True
                    table_id = None
                    break  # Skip all table_ids in id_list
                else:
                    print("Invalid input. Please enter y or n.")
        if table_id is None:
            continue  # Skip to next table_id

        if verbose: print(f"Generating table {table_id}...")

        matches = glob.glob(os.path.join(table_dir, f"*{table_id}_final.csv"))
        # TODO: error handling
        if len(matches) == 0:
            # Try again without the _final suffix
            # TODO: WW_4a and WW_4b must be merged if _final doesn't exist
            print(f"No table {table_id}_final found! Trying without the _final suffix.")
            matches = glob.glob(os.path.join(table_dir, f"*{table_id}.csv"))
            if len(matches) == 0:
                print(f"No table {table_id} found!")
                continue
        table = matches[0]
        if verbose: print(f"Reading: {table}")

        # Read in the csv
        df = pd.read_csv(table, encoding='utf-8-sig')

        # Check if this is an elevation band table by looking for "Elevation Band" in header
        is_elevation_table = "Elevation Band" in df.iloc[0].astype(str).values
        print(df.iloc[0].astype(str).values)
        print(f"Is elevation table: {is_elevation_table}")

        # df = df.iloc[:, 1:] # Drop the first column containing indices, no longer necessary

        # Format SNODAS dates to 1 decimal place (matching our SWE precision)
        last_col = df.columns[-1]
        df.loc[1:, last_col] = pd.to_numeric(df.loc[1:, last_col], errors="coerce").round(1)

        # Check how many dates have data (first report does not have a previous date)
        row0 = df.iloc[0].astype(str)
        date_count = row0.str.contains("Avg").sum()
        if verbose: print(f"Date count: {date_count}")
        if date_count == 0:
            # TODO: error handling
            pass

        # Determine column offset based on table type
        col_offset = 2 if is_elevation_table else 1

        # Get current date and previous date if it exists
        if date_count > 1:
            previous_date = df.iloc[0, col_offset].strip("%").replace(" Avg.", "")
            current_date = df.iloc[0, col_offset+1].strip("%").replace(" Avg.", "")
        else:
            current_date = df.iloc[0, col_offset].strip("%").replace(" Avg.", "")

        # Get header data
        headers = {}
        if is_elevation_table:
            headers[""] = ["Elevation Band"]
        headers["% of Average"] = (
            [previous_date, current_date] if date_count > 1 else [current_date]
        )
        headers["SWE (in)"] = (
            [previous_date, current_date] if date_count > 1 else [current_date]
        )
        headers[" "] = ["SCA"]
        if report_type == "WW":
            headers["  "] = ["Vol. (AF)"]
        else: # SNM
            headers["  "] = [r"Vol. (AF)$\ddagger$"]
        headers["    "] = ["Area (mi$^2$)"]
        headers["Pillows"] = (
            [previous_date, current_date] if date_count > 1 else [current_date]
        )
        surveys = "Surveys" in df.iloc[0].astype(str).values
        if surveys:
            if verbose: print("Including surveys.")
            headers["Surveys"] = [current_date]

        headers["SNODAS* (in)"] = [current_date]

        # Determine which footer notes to include
        aso_corrected = df.iloc[:, 0].astype(str).str.contains("§").any()
        fsca_issue = df.iloc[:, 0].astype(str).str.contains("+", regex=False).any()
        high_pct_avg = df.apply(lambda col: col.astype(str).str.contains("†", regex=False)).any().any()
        is_ww = (report_type == "WW")
        is_socn = (is_ww and table_id == "03")

        if verbose:
            print(f"ASO Corrected: {aso_corrected}, fSCA Issue: {fsca_issue}, High % Avg: {high_pct_avg}, Is SOCN: {is_socn}")

        # Escape LaTeX special characters in basin names (first column)
        df.iloc[:, 0] = df.iloc[:, 0].astype(str).apply(escape_latex)

        # Load table template
        templates_dir = Path(__file__).parent.parent / "report_templates"
        env = Environment(loader=FileSystemLoader(str(templates_dir)),
                          trim_blocks=True, lstrip_blocks=True)

        # Select template based on table type
        if standalone:
            template_name = (
                "TEMPLATE_Elev_SWE_Table_standalone.tex" if is_elevation_table
                else "TEMPLATE_SWE_Table_standalone.tex"
            )
        else:
            template_name = "TEMPLATE_Elev_SWE_Table.tex" if is_elevation_table else "TEMPLATE_SWE_Table.tex"
        template = env.get_template(template_name)

        latex_table = template.render(
            df=df,
            title=table_data[table_id]["title"] if isinstance(table_data[table_id], dict) else table_data[table_id],
            headers=headers,
            date=date_str,
            surveys=surveys,
            aso_corrected=aso_corrected,
            fsca_issue=fsca_issue,
            high_pct_avg=high_pct_avg,
            is_ww=is_ww,
            is_socn=is_socn,
        )

        # Special handling for the dagger character
        latex_table = latex_table.replace('†', r'$\dagger$')

        # Write table to LaTeX file in the output directory
        os.makedirs(get_output_dir(date, report_type), exist_ok=True)
        if verbose: print(f"Writing table to {output_filepath}")
        with open(output_filepath, "w", encoding="utf-8") as f:
            f.write(latex_table)
        if verbose: print(f"Finished generating Table{table_id}.")


def main():
    # Parse input arguments and flags, see top of file for argument usage examples
    parser = argparse.ArgumentParser()
    parser.add_argument("report_type", type=str, help="Acceptable report types: WW, SNM")
    parser.add_argument("date", type=int, help="Date to process (YYYYMMDD)")
    parser.add_argument("--tables", default="all", type=str, help="Regex pattern(s) for table IDs to generate")
    parser.add_argument("-s", "--standalone", action="store_true", help="Generate standalone PDFs instead of embeddable .tex files")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output messages")
    parser.add_argument("-u", "--prompt_user", action="store_true", help="Prompt the user before overwriting or automatically selecting files")
    args = parser.parse_args()

    # Check report type is valid
    if args.report_type not in ["WW", "SNM"]:
        raise Exception(f"Unrecognized report type: {args.report_type}")

    # TODO: check date format and range

    # Generate tables
    generate_tables(args.report_type, args.date, args.tables, args.verbose, args.prompt_user, args.standalone)

    # Compile SNM standalone tables and convert to jpg
    if args.standalone and args.report_type == "SNM":
        report_dir = Path(get_output_dir(args.date, args.report_type)).parent  # TEXtables/ -> Report/
        id_list = interpret_ids(args.tables, args.report_type)
        for table_id in id_list:
            tex_path = Path(get_output_dir(args.date, args.report_type)) / f"{args.date}_SNM_Table{table_id}_standalone.tex"
            # .tex and .pdf are saved to TEXtables/; all other auxiliary files are saved to LaTeX/
            pdf_path = compile_standalone_table(tex_path, args.verbose)
            if pdf_path:
                jpg_id = snm_table_data[table_id]["jpg_id"]
                jpg_stem = f"{args.date}_SNM_Table{jpg_id}"
                # Convert pdf to jpg with pymupdf; .jpg is saved to Report/
                convert_pdf_to_jpg(pdf_path, report_dir, args.verbose, jpg_stem, args.prompt_user)

if __name__ == "__main__":
    main()